diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=true
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
uver.name=Dohyun Kim
use.email=spurs96alli@gmail.com
core.autocrlf=true
user.name=ehgus964
user.email=ehgus964@gmail.com
credential.https://lab.ssafy.com.provider=generic
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
user.name=ehgus964
user.email=ehgus964@gmail.com
remote.origin.url=https://github.com/Dohyun-Kimm/Algorithm_Study.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
